version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.22.6
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8081:8080"
      - "50052:50051"
    restart: no
    environment:
      - CONTEXTIONARY_URL=http://t2v-contextionary:9999
      - QUERY_DEFAULTS_LIMIT=25
      - QUERY_MAXIMUM_RESULTS=10000
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - ENABLE_MODULES=text2vec-contextionary
      - CLUSTER_HOSTNAME=node1
      - AUTOSCHEMA_ENABLED=false
    volumes:
      - store:/var/lib/weaviate
    depends_on:
      - t2v-contextionary

  t2v-contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - "9998:9999"
    environment:
      - OCCURRENCE_WEIGHT_LINEAR_FACTOR=0.75
      - EXTENSIONS_STORAGE_MODE=weaviate
      - EXTENSIONS_STORAGE_ORIGIN=http://weaviate:8080
      - NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE=5
      - ENABLE_COMPOUND_SPLITTING=false

volumes:
  store:
