version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.14.1
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8084:8080"
    restart: no
    environment:
      - CONTEXTIONARY_URL=http://contextionary:9999
      - QNA_INFERENCE_API=http://qna-transformers:8080
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - ENABLE_MODULES=text2vec-contextionary,qna-transformers
      - CLUSTER_HOSTNAME=node1
    depends_on:
      - contextionary
      - qna-transformers

  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
    ports:
      - "9997:9999"
    environment:
      - OCCURRENCE_WEIGHT_LINEAR_FACTOR=0.75
      - EXTENSIONS_STORAGE_MODE=weaviate
      - EXTENSIONS_STORAGE_ORIGIN=http://weaviate:8080
      - NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE=5
      - ENABLE_COMPOUND_SPLITTING=false

  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      - ENABLE_CUDA=0
