version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.20.5
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8085:8080"
    restart: no
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - ENABLE_MODULES=text2vec-contextionary,img2vec-neural
      - CONTEXTIONARY_URL=http://contextionary:9999
      - IMAGE_INFERENCE_API=http://i2v-neural:8080
    depends_on:
      - contextionary
      - i2v-neural

  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
    ports:
      - "9999:9999"
    environment:
      - OCCURRENCE_WEIGHT_LINEAR_FACTOR=0.75
      - EXTENSIONS_STORAGE_MODE=weaviate
      - EXTENSIONS_STORAGE_ORIGIN=http://weaviate:8080
      - NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE=5
      - ENABLE_COMPOUND_SPLITTING=false

  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
